TOP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

# Create the build directory and invoke cmake
all:
	cd ${TOP_DIR} && make

debug:
	cd ${TOP_DIR} && make BUILD_TYPE=Debug

release:
	cd ${TOP_DIR} && make BUILD_TYPE=Release

profile:
	cd ${TOP_DIR} && make BUILD_TYPE=Profile

RelWithDebInfo:
	cd ${TOP_DIR} && make BUILD_TYPE=RelWithDebInfo

clean:
	-cd ${TOP_DIR} && make clean
	rm -rf bin lib

test: all
	cd ${TOP_DIR} && make -k $@